apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-rollback-role
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["create", "update", "rollback"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-rollback-rolebinding
subjects:
- kind: User # Can also be "Group such as the dev team"
  name: deploy-rollback-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy-rollback-role
  apiGroup: rbac.authorization.k8s.io

