apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
type: Opaque
data:
  users-username: YWRtaW4=
  shift-username: c3VwZXJ1c2Vy 
  users-password: cGFzc3dvcmQx
  shifts-password: cGFzc3dvcmQy
